# A program to output verified acronyms. Takes as input
# a CSV file with [long_form,short_form] pairs in any
# source language supported by the Google API. Output
# is a tab-separated value file with candidate translations
# generated by the model, IDs of verified sources, and
# selected translation candidate

import sys, os
import arXiv_check, pubmed_check, predict, translate
import csv
import os

TERM_FILE=sys.argv[1]
NUM_CANDIDATES=5

def main():

    long_forms = []
    short_forms = []
    
    with open(TERM_FILE, 'r') as fd:
        full_terms = fd.readlines()
        for term in full_terms:
            long_forms.append(term.split(',')[0])
            short_forms.append(term.split(',')[1].strip('\n'))

    with open('translations.tsv', 'w') as fd:
        tsv_writer = csv.writer(fd, delimiter='\t')
        tsv_writer.writerow(["lf_fr", "sf_fr", "lf_en", "sf_google", "sf_model", "verified_google", "verified_model", "true_sf"])
        for term in enumerate(long_forms):
            print(term[1])
            # translate term with google, store under lf_en
            # translate short form with google
            google_full = translate.translate_text(f"{long_forms[term[0]]} ({short_forms[term[0]]})")
            google_split = google_full.split('(')
            long_form_translated = google_split[0].strip('\n ')
            google_acronym = google_split[1][:-1]
            # use model to get acronym
            model_prediction = predict.predict(f"{long_form_translated} ([MASK])")
            model_acronym = []
            for acronym_pair in model_prediction:
                model_acronym.append(acronym_pair.split('(')[1][:-1])
            true_sf = None
            # verify google
            google_verified = arXiv_check.check_acronym(long_form_translated + " ("+  google_acronym + ")") or pubmed_check.check_acronym(long_form_translated + " ("+  google_acronym + ")")
            if len(google_verified) > 1:
                true_sf = google_acronym
            # verify acronym
            candidate = 0
            model_verified = []
            if not true_sf:
                while len(model_verified) < 2 and candidate < NUM_CANDIDATES:
                    model_verified = arXiv_check.check_acronym(long_form_translated + " (" + model_acronym[candidate] + ")") or pubmed_check.check_acronym(long_form_translated + " (" + model_acronym[candidate] + ")")
                    if len(model_verified) == 2 and not true_sf:
                        true_sf = model_acronym[candidate]
                    candidate += 1
            else:
                for acronym in model_acronym:
                    if acronym == google_acronym:
                        model_verified = google_verified
                        break
            tsv_writer.writerow([term[1], short_forms[term[0]], long_form_translated, google_acronym, model_acronym, google_verified, model_verified, str(true_sf)])
            
if __name__ == "__main__":
    main()
